version: '3.8'

# Create a configuration postgres sql e redis
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: nexus_password
      POSTGRES_DB: nexus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: nexus_user
      DB_PASSWORD: nexus_password
      DB_NAME: nexus_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""

volumes:
  postgres_data_v2:
  redis_data:
